name: fitness_ai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  cloud_firestore: ^4.7.0
  provider: ^6.0.0
  google_fonts: ^6.1.0
  flutter_vector_icons: ^2.0.0
  bootstrap_icons: ^1.10.0
  icons_plus: ^5.0.0
  flutter_dotenv: ^5.1.0
  fl_chart: any
  firebase_auth: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env

dependency_overrides:
  fl_chart:
    git:
      url: https://github.com/imaNNeoFighT/fl_chart.git
      ref: main
