// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTsvfqCRjEPxzulnz3ydrlnC2dWV9g5UA',
    appId: '1:219551804012:web:90855a8b1a619f66ebc649',
    messagingSenderId: '219551804012',
    projectId: 'fitness-ai-3be07',
    authDomain: 'fitness-ai-3be07.firebaseapp.com',
    storageBucket: 'fitness-ai-3be07.firebasestorage.app',
    measurementId: 'G-JSC31JRBW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmsAH1g3crsw5itRm3ns-0I37IJJ6YhdQ',
    appId: '1:219551804012:android:b264cbdfcd1e0752ebc649',
    messagingSenderId: '219551804012',
    projectId: 'fitness-ai-3be07',
    storageBucket: 'fitness-ai-3be07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA-yon5Z16vbH7mA5nOvD49IXDjZ55bOY',
    appId: '1:219551804012:ios:26f468df117c8307ebc649',
    messagingSenderId: '219551804012',
    projectId: 'fitness-ai-3be07',
    storageBucket: 'fitness-ai-3be07.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAi',
  );
}
